CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;




DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260220102909_InitialCreate_Porstgres') THEN
    CREATE TABLE tbl_emp (
        emp_id integer GENERATED BY DEFAULT AS IDENTITY,
        emp_name character varying(50) NOT NULL,
        emp_phone character varying(50) NOT NULL,
        emp_email character varying(50) NOT NULL,
        emp_role character varying(10) NOT NULL,
        emp_pass character varying(255) NOT NULL,
        "IsActive" boolean NOT NULL,
        CONSTRAINT "PK_tbl_emp" PRIMARY KEY (emp_id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260220102909_InitialCreate_Porstgres') THEN
    CREATE TABLE tbl_order_items (
        order_item_id integer GENERATED BY DEFAULT AS IDENTITY,
        order_id integer,
        part_id integer,
        quantity integer,
        unit_price numeric(18,2),
        total_price numeric(18,2),
        CONSTRAINT "PK_tbl_order_items" PRIMARY KEY (order_item_id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260220102909_InitialCreate_Porstgres') THEN
    CREATE TABLE tbl_orders (
        order_id integer GENERATED BY DEFAULT AS IDENTITY,
        u_id integer NOT NULL,
        total_amount numeric(18,2),
        status text,
        created_at timestamp with time zone,
        CONSTRAINT "PK_tbl_orders" PRIMARY KEY (order_id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260220102909_InitialCreate_Porstgres') THEN
    CREATE TABLE tbl_part (
        part_id integer GENERATED BY DEFAULT AS IDENTITY,
        emp_id integer NOT NULL,
        part_name text,
        part_detail character varying(100) NOT NULL,
        part_price numeric(18,2) NOT NULL,
        part_stock integer NOT NULL,
        part_image character varying(100) NOT NULL,
        idt timestamp with time zone NOT NULL,
        CONSTRAINT "PK_tbl_part" PRIMARY KEY (part_id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260220102909_InitialCreate_Porstgres') THEN
    CREATE TABLE tbl_user (
        u_id integer GENERATED BY DEFAULT AS IDENTITY,
        u_name character varying(50) NOT NULL,
        u_phone character varying(50) NOT NULL,
        u_email character varying(50) NOT NULL,
        u_pass character varying(255) NOT NULL,
        u_role text,
        CONSTRAINT "PK_tbl_user" PRIMARY KEY (u_id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260220102909_InitialCreate_Porstgres') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260220102909_InitialCreate_Porstgres', '8.0.8');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260226171009_FixPartTimeStampTimeZone') THEN
    ALTER TABLE tbl_part ALTER COLUMN idt SET DEFAULT (NOW());
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260226171009_FixPartTimeStampTimeZone') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260226171009_FixPartTimeStampTimeZone', '8.0.8');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260228173417_AddCreatedAndUpdatedToPart') THEN
    ALTER TABLE tbl_part RENAME COLUMN idt TO created_at;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260228173417_AddCreatedAndUpdatedToPart') THEN
    ALTER TABLE tbl_part ADD updated_at timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260228173417_AddCreatedAndUpdatedToPart') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260228173417_AddCreatedAndUpdatedToPart', '8.0.8');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260302105601_RemoveUpdatedAtDefault') THEN
    ALTER TABLE tbl_part ALTER COLUMN updated_at DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260302105601_RemoveUpdatedAtDefault') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260302105601_RemoveUpdatedAtDefault', '8.0.8');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260302111035_RemoveUpdatedDbDefault') THEN
    ALTER TABLE tbl_part ALTER COLUMN updated_at DROP NOT NULL;
    ALTER TABLE tbl_part ALTER COLUMN updated_at DROP DEFAULT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260302111035_RemoveUpdatedDbDefault') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260302111035_RemoveUpdatedDbDefault', '8.0.8');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260309173006_IncreasePartImageLength') THEN
    ALTER TABLE tbl_part ALTER COLUMN part_image TYPE character varying(500);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260309173006_IncreasePartImageLength') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260309173006_IncreasePartImageLength', '8.0.8');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260319080507_Add_PartDescription') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260319080507_Add_PartDescription', '8.0.8');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260324173225_AddImageKeyPart') THEN
    ALTER TABLE tbl_part ADD "part-image_key" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260324173225_AddImageKeyPart') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260324173225_AddImageKeyPart', '8.0.8');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260401134131_AddUpdatedDateToCart') THEN
    ALTER TABLE tbl_cart ADD "UpdatedDate" timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260401134131_AddUpdatedDateToCart') THEN
    ALTER TABLE tbl_cart ADD "UserId" integer;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260401134131_AddUpdatedDateToCart') THEN
    CREATE INDEX "IX_tbl_cart_part_id" ON tbl_cart (part_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260401134131_AddUpdatedDateToCart') THEN
    CREATE INDEX "IX_tbl_cart_UserId" ON tbl_cart ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260401134131_AddUpdatedDateToCart') THEN
    ALTER TABLE tbl_cart ADD CONSTRAINT "FK_tbl_cart_tbl_part_part_id" FOREIGN KEY (part_id) REFERENCES tbl_part (part_id) ON DELETE CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260401134131_AddUpdatedDateToCart') THEN
    ALTER TABLE tbl_cart ADD CONSTRAINT "FK_tbl_cart_tbl_user_UserId" FOREIGN KEY ("UserId") REFERENCES tbl_user (u_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260401134131_AddUpdatedDateToCart') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260401134131_AddUpdatedDateToCart', '8.0.8');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260401164147_SetDefaultAddedDateForCart') THEN
    ALTER TABLE tbl_cart ALTER COLUMN added_date SET DEFAULT (Now());
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260401164147_SetDefaultAddedDateForCart') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260401164147_SetDefaultAddedDateForCart', '8.0.8');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260407091931_RemoveDuplicateUserIdFromCart') THEN
    ALTER TABLE tbl_cart DROP CONSTRAINT "FK_tbl_cart_tbl_user_UserId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260407091931_RemoveDuplicateUserIdFromCart') THEN
    DROP INDEX "IX_tbl_cart_UserId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260407091931_RemoveDuplicateUserIdFromCart') THEN
    ALTER TABLE tbl_cart DROP COLUMN "UserId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260407091931_RemoveDuplicateUserIdFromCart') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260407091931_RemoveDuplicateUserIdFromCart', '8.0.8');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260415072309_AddInvoiceFieldsToOrder') THEN
    UPDATE tbl_orders SET total_amount = 0.0 WHERE total_amount IS NULL;
    ALTER TABLE tbl_orders ALTER COLUMN total_amount SET NOT NULL;
    ALTER TABLE tbl_orders ALTER COLUMN total_amount SET DEFAULT 0.0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260415072309_AddInvoiceFieldsToOrder') THEN
    UPDATE tbl_orders SET status = '' WHERE status IS NULL;
    ALTER TABLE tbl_orders ALTER COLUMN status SET NOT NULL;
    ALTER TABLE tbl_orders ALTER COLUMN status SET DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260415072309_AddInvoiceFieldsToOrder') THEN
    UPDATE tbl_orders SET created_at = CURRENT_TIMESTAMP WHERE created_at IS NULL;
    ALTER TABLE tbl_orders ALTER COLUMN created_at SET NOT NULL;
    ALTER TABLE tbl_orders ALTER COLUMN created_at SET DEFAULT (CURRENT_TIMESTAMP);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260415072309_AddInvoiceFieldsToOrder') THEN
    ALTER TABLE tbl_orders ADD invoice_number text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260415072309_AddInvoiceFieldsToOrder') THEN
    ALTER TABLE tbl_orders ADD subtotal_amount numeric NOT NULL DEFAULT 0.0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260415072309_AddInvoiceFieldsToOrder') THEN
    ALTER TABLE tbl_orders ADD tax_amount numeric NOT NULL DEFAULT 0.0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260415072309_AddInvoiceFieldsToOrder') THEN
    UPDATE tbl_order_items SET unit_price = 0.0 WHERE unit_price IS NULL;
    ALTER TABLE tbl_order_items ALTER COLUMN unit_price SET NOT NULL;
    ALTER TABLE tbl_order_items ALTER COLUMN unit_price SET DEFAULT 0.0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260415072309_AddInvoiceFieldsToOrder') THEN
    UPDATE tbl_order_items SET total_price = 0.0 WHERE total_price IS NULL;
    ALTER TABLE tbl_order_items ALTER COLUMN total_price SET NOT NULL;
    ALTER TABLE tbl_order_items ALTER COLUMN total_price SET DEFAULT 0.0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260415072309_AddInvoiceFieldsToOrder') THEN
    UPDATE tbl_order_items SET quantity = 0 WHERE quantity IS NULL;
    ALTER TABLE tbl_order_items ALTER COLUMN quantity SET NOT NULL;
    ALTER TABLE tbl_order_items ALTER COLUMN quantity SET DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260415072309_AddInvoiceFieldsToOrder') THEN
    UPDATE tbl_order_items SET part_id = 0 WHERE part_id IS NULL;
    ALTER TABLE tbl_order_items ALTER COLUMN part_id SET NOT NULL;
    ALTER TABLE tbl_order_items ALTER COLUMN part_id SET DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260415072309_AddInvoiceFieldsToOrder') THEN
    UPDATE tbl_order_items SET order_id = 0 WHERE order_id IS NULL;
    ALTER TABLE tbl_order_items ALTER COLUMN order_id SET NOT NULL;
    ALTER TABLE tbl_order_items ALTER COLUMN order_id SET DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260415072309_AddInvoiceFieldsToOrder') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260415072309_AddInvoiceFieldsToOrder', '8.0.8');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260417111119_AddOrderIdempotency') THEN
    CREATE TABLE "OrderIdempotencies" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "IdempotencyKey" text,
        "UserId" integer NOT NULL,
        "OrderId" integer NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        CONSTRAINT "PK_OrderIdempotencies" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260417111119_AddOrderIdempotency') THEN
    CREATE UNIQUE INDEX "IX_OrderIdempotencies_UserId_IdempotencyKey" ON "OrderIdempotencies" ("UserId", "IdempotencyKey");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260417111119_AddOrderIdempotency') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260417111119_AddOrderIdempotency', '8.0.8');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260420064014_MakeIdempotencyKeyNotNull') THEN
    ALTER TABLE "OrderIdempotencies" ALTER COLUMN "IdempotencyKey" SET NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260420064014_MakeIdempotencyKeyNotNull') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260420064014_MakeIdempotencyKeyNotNull', '8.0.8');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260423130547_SyncWithProduction') THEN
    CREATE INDEX "IX_tbl_order_items_order_id" ON tbl_order_items (order_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260423130547_SyncWithProduction') THEN
    CREATE INDEX "IX_tbl_order_items_part_id" ON tbl_order_items (part_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260423130547_SyncWithProduction') THEN
    ALTER TABLE tbl_order_items ADD CONSTRAINT "FK_tbl_order_items_tbl_orders_order_id" FOREIGN KEY (order_id) REFERENCES tbl_orders (order_id) ON DELETE CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260423130547_SyncWithProduction') THEN
    ALTER TABLE tbl_order_items ADD CONSTRAINT "FK_tbl_order_items_tbl_part_part_id" FOREIGN KEY (part_id) REFERENCES tbl_part (part_id) ON DELETE CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260423130547_SyncWithProduction') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260423130547_SyncWithProduction', '8.0.8');
    END IF;
END $EF$;
COMMIT;

