CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260220102909_InitialCreate_Porstgres') THEN
    CREATE TABLE tbl_cart (
        cart_id integer GENERATED BY DEFAULT AS IDENTITY,
        u_id integer NOT NULL,
        part_id integer NOT NULL,
        quantity integer NOT NULL,
        added_date timestamp with time zone,
        CONSTRAINT "PK_tbl_cart" PRIMARY KEY (cart_id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260220102909_InitialCreate_Porstgres') THEN
    CREATE TABLE tbl_emp (
        emp_id integer GENERATED BY DEFAULT AS IDENTITY,
        emp_name character varying(50) NOT NULL,
        emp_phone character varying(50) NOT NULL,
        emp_email character varying(50) NOT NULL,
        emp_role character varying(10) NOT NULL,
        emp_pass character varying(255) NOT NULL,
        "IsActive" boolean NOT NULL,
        CONSTRAINT "PK_tbl_emp" PRIMARY KEY (emp_id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260220102909_InitialCreate_Porstgres') THEN
    CREATE TABLE tbl_order_items (
        order_item_id integer GENERATED BY DEFAULT AS IDENTITY,
        order_id integer,
        part_id integer,
        quantity integer,
        unit_price numeric(18,2),
        total_price numeric(18,2),
        CONSTRAINT "PK_tbl_order_items" PRIMARY KEY (order_item_id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260220102909_InitialCreate_Porstgres') THEN
    CREATE TABLE tbl_orders (
        order_id integer GENERATED BY DEFAULT AS IDENTITY,
        u_id integer NOT NULL,
        total_amount numeric(18,2),
        status text,
        created_at timestamp with time zone,
        CONSTRAINT "PK_tbl_orders" PRIMARY KEY (order_id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260220102909_InitialCreate_Porstgres') THEN
    CREATE TABLE tbl_part (
        part_id integer GENERATED BY DEFAULT AS IDENTITY,
        emp_id integer NOT NULL,
        part_name text,
        part_detail character varying(100) NOT NULL,
        part_price numeric(18,2) NOT NULL,
        part_stock integer NOT NULL,
        part_image character varying(100) NOT NULL,
        idt timestamp with time zone NOT NULL,
        CONSTRAINT "PK_tbl_part" PRIMARY KEY (part_id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260220102909_InitialCreate_Porstgres') THEN
    CREATE TABLE tbl_user (
        u_id integer GENERATED BY DEFAULT AS IDENTITY,
        u_name character varying(50) NOT NULL,
        u_phone character varying(50) NOT NULL,
        u_email character varying(50) NOT NULL,
        u_pass character varying(255) NOT NULL,
        u_role text,
        CONSTRAINT "PK_tbl_user" PRIMARY KEY (u_id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260220102909_InitialCreate_Porstgres') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260220102909_InitialCreate_Porstgres', '8.0.8');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260226171009_FixPartTimeStampTimeZone') THEN
    ALTER TABLE tbl_part ALTER COLUMN idt SET DEFAULT (NOW());
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260226171009_FixPartTimeStampTimeZone') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260226171009_FixPartTimeStampTimeZone', '8.0.8');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260228173417_AddCreatedAndUpdatedToPart') THEN
    ALTER TABLE tbl_part RENAME COLUMN idt TO created_at;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260228173417_AddCreatedAndUpdatedToPart') THEN
    ALTER TABLE tbl_part ADD updated_at timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260228173417_AddCreatedAndUpdatedToPart') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260228173417_AddCreatedAndUpdatedToPart', '8.0.8');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260302105601_RemoveUpdatedAtDefault') THEN
    ALTER TABLE tbl_part ALTER COLUMN updated_at DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260302105601_RemoveUpdatedAtDefault') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260302105601_RemoveUpdatedAtDefault', '8.0.8');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260302111035_RemoveUpdatedDbDefault') THEN
    ALTER TABLE tbl_part ALTER COLUMN updated_at DROP NOT NULL;
    ALTER TABLE tbl_part ALTER COLUMN updated_at DROP DEFAULT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260302111035_RemoveUpdatedDbDefault') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260302111035_RemoveUpdatedDbDefault', '8.0.8');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260309173006_IncreasePartImageLength') THEN
    ALTER TABLE tbl_part ALTER COLUMN part_image TYPE character varying(500);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260309173006_IncreasePartImageLength') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260309173006_IncreasePartImageLength', '8.0.8');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260319080507_Add_PartDescription') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260319080507_Add_PartDescription', '8.0.8');
    END IF;
END $EF$;
COMMIT;

